/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

/*
Obsidian Annotator Plugin
A plugin for Obsidian that allows you to annotate PDFs and EPUBs.
GitHub: https://github.com/elias-sundqvist/obsidian-annotator
*/

'use strict';

// This is a placeholder file. Please install the full plugin from:
// 1. Obsidian Settings -> Community Plugins -> Browse
// 2. Search for "Annotator"
// 3. Click Install and Enable

// Or download from: https://github.com/elias-sundqvist/obsidian-annotator/releases

module.exports = class AnnotatorPlugin {
    constructor() {
        this.pluginName = 'Annotator';
    }

    async onload() {
        console.log('Annotator plugin placeholder loaded');
    }

    async onunload() {
        console.log('Annotator plugin unloaded');
    }
};